### ISSUE TITLE
How can I show ImGui.BeginTabItem without the X (Close)??

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Sewer56/DearImguiSharp#11]
Hello how are you? Sorry to bother you again, I just couldn't find a solution. 

How could I show **ImGui.BeginTabItem** without the **X** (Close)??

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/1316fc7f-d219-4792-867d-fa79fa4e0cd3)

**Comment by Sewer56** [comment]
I haven't worked with tabs before, so I don't know.
It's been forever since I've worked with Dear ImGui.

I suggest checking the example code in `imgui.h`

**Comment by Sewer56** [comment]
(I've also mentioned this in the past. But play nice, and don't cheat in online games)

**Comment by DestroyerDarkNess** [comment]
umm, I found [this](https://github.com/ocornut/imgui/issues/1305)

I guess I'll have to modify DearImguiSharp. to be able to pass the ref p_open parameter, as null, but I don't know if it works. I will update tomorrow. since in my country it is very late.

> (I've also mentioned this in the past. But play nice, and don't cheat in online games)

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/ff40e4a4-3c65-4394-be4e-464e38576f5e)

**Comment by Sewer56** [comment]
You can always check the `Internal` API. IIRC I went out of my way to expose the raw bindings without the sugar from the bindings generator.

**Comment by DestroyerDarkNess** [comment]
OMG. This worked perfectly, thank you.

```c#
 public unsafe static bool BeginTabItem(string label, int flags)
 {
     bool* p_open2 = null;
     return ImGui.__Internal.BeginTabItem(label, p_open2, flags);
 }

```

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/fed230b9-a02f-415c-9e66-e7da38824c94)
