### ISSUE TITLE
ImplWin32_WndProcHandler |  IO.MouseDown NOT Working.

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Sewer56/DearImguiSharp#6]
Hello, I have a little problem. "ImplWin32_WndProcHandler" does not work for me

I replaced Imgui.NET with your library. Since I use the .net framework, compile DearImguiSharp to the NETStandard 2.0 target.

With Imgui.net I have several ways to hook Wndproc: "[HERE](https://github.com/DestroyerDarkNess/RenderSpy/tree/main/RenderSpy/Inputs)"

but although the hook works perfectly, when I pass them to DearImguiSharp->ImplWin32_WndProcHandler, it doesn't work and I can't interact with the menu.

So I decided to use the old reliable one:

`
 IO.MouseDrawCursor = true;

  int LButton = WinApi.GetAsyncKeyState(Keys.LButton); IO.MouseDown[0] = (LButton != 0);

  int RButton = WinApi.GetAsyncKeyState(Keys.RButton); IO.MouseDown[1] = (RButton != 0);

  int MButton = WinApi.GetAsyncKeyState(Keys.MButton); IO.MouseDown[2] = (MButton != 0);

  int XButton1 = WinApi.GetAsyncKeyState(Keys.XButton1); IO.MouseDown[3] = (XButton1 != 0);

  int XButton2 = WinApi.GetAsyncKeyState(Keys.XButton2); IO.MouseDown[4] = (XButton2 != 0);
`

**And to my surprise, the mouse clicks are not sent, I don't know what is happening, I need help.**

**Comment by Sewer56** [comment]
See what happens if you use https://github.com/Sewer56/Reloaded.Imgui.Hook as reference.

There's a sample [Reloaded-II](https://github.com/Reloaded-Project/Reloaded-II) plugin in there (`Reloaded.ImGui.TestMod`). Download Reloaded, run it, build the plugin, enable it and see if you get working cursor inside the target process/game you are working with.

If the reference implementation I have works, you will at least have something to compare your code against.

**Comment by DestroyerDarkNess** [comment]
Hello, thanks for answering, Always respond quickly. xD

Your mod works perfectly, try to copy your WndProc Hook , but using MinHook.NET.

WndProc hook aside, any ideas why IO.MouseDown isn't working? .

I'll update when I'm done.

**### Edit:** 

I have another small doubt, since I am using .net framework, I cannot pass the type `void* hwnd` in `ImplWin32_WndProcHandler`.

Therefore I changed it to the `IntPtr hwnd` type, could that be the problem?

`
  [DllImport("cimgui.dll", CallingConvention = CallingConvention.Cdecl, EntryPoint = "ImGui_ImplWin32_WndProcHandler")]
  public static extern unsafe IntPtr ImplWin32_WndProcHandler(IntPtr hwnd, uint msg, IntPtr wParam, IntPtr lParam);
`

Why do you handle hwn as a void* type instead of IntPtr ?

PS: I don't know modern c#, maybe I'm asking something obvious.

**Comment by DestroyerDarkNess** [comment]
Well, I don't actually know what happened, but this solved it for me:

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/2be46217-6ee9-4bba-8af5-d3bc2f70c276)

Now ImplWin32_WndProcHandler is working normally. I'll let you close the topic, if you want to answer something.

**Comment by Sewer56** [comment]
Did that actually fix it for you? Seems pretty strange.

`void*` vs `IntPtr` shouldn't make a difference, both are effectively `native sized int` (nint), and should generate the same code. IntPtr mainly exists to be a CLS compliant (can be used in other .NET languages) representation of a native sized int.

**Comment by DestroyerDarkNess** [comment]
Yes, that's why I said I don't know what's really happening. It's really strange, I was reading this: "[HERE](https://github.com/dotnet/roslyn/issues/44810)", which confirms what you say.

I'll record a little video.

**### Edit:** 

A small video:

https://github.com/Sewer56/DearImguiSharp/assets/32405118/5196cde8-e372-4824-9e33-e879f43af6ab

**By the way, I still can't simulate clicks with: IO.MouseDown. If you have time to check that, please let me know.**

**Comment by Sewer56** [comment]
Hey, glad to see that it works.

> I still can't simulate clicks with: IO.MouseDown

I'd probably be in the same boat as you on this one, I haven't used Dear imgui in around 2.5 years now; a lot of other projects to do, so it's been a very long time.

**Comment by DestroyerDarkNess** [comment]
Thanks for helping me, I'm keeping an eye on this repository, in case you decide to update it, great library.
