### ISSUE TITLE
Critical error when assigning values to Properties.

### ISSUE THREAD

**Issue by DestroyerDarkNess** [Sewer56/DearImguiSharp#7]
``Hello, it's me again. I know you're busy, but I have to report this bug.

I will try to explain it, I will use **ImGui Style** and its **Colors Property** as an example.

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/c503a791-90d2-4998-8c66-a8e8b7aa4498)

When Obtaining a color (type ImVec4) from that property, it works perfectly, the problem is when trying to Set the Color property.

```C#
var style = DearImguiSharp.ImGui.GetStyle();
style.Colors[(int)ImGuiCol.Text] = new ImVec4 { W = 0.2f, X = 0.6f, Y = 1.0f, Z = 1.0f };
```

There is no need to explain the code, but the problem is that this code does not set the Colors property, what this code does is directly set the ImVec4 object to another ImVec4.

What I mean is that the Set of the Colors property is not being executed. 

The problem is that this means that you cannot change the urinary value of that property.

The somewhat vague solution I have is to directly change the ImVec4 values.

```C#
var style = DearImguiSharp.ImGui.GetStyle();
ImVec4 TextColor = style.Colors[(int)ImGuiCol.Text];
TextColor.W = 0.2f;
TextColor.X = 0.6f;
TextColor.Y = 1.0f;
TextColor.Z = 1.0f;
```

By the way, modifying the __Instance of the old ImVec4 class with the new instance of the new one does not work directly. (At least it doesn't work when I write it directly, since most of the code is written in a somewhat abstract way using pure pointers to functions. I have never written code that way)

This same problem occurs with IO.MouseDown .

To solve it, you would either have to rewrite the properties, or simply add auxiliary methods to set values to the Classes, such as ImVec4.

I do not know if I explained well.

**Comment by Sewer56** [comment]
Pretty sure I've ran into this before, given I wrote the following code to make a 'Reloaded' theme for Dear ImGui.

https://github.com/Sewer56/Riders.Tweakbox/blob/be929f5fabc43ff2e4c20dbc3919fb1346622ced/Submodules/Sewer56.Imgui/Shell/Misc/Shell.cs#L101

In any case, this code is autogenerated by CppSharp from the original ImGui headers. If you want to try fixup the output of this, consider editing the `CodeGenerator` project. I originally built this because at the time, ImGui.NET was many versions behind, and hard to fix for the current version; so I tried to make a library with 'minimal maintenance required' for updates. I only fixed what was completely broken.

Alternatively, feel free to write your own extension method to manipulate the colours directly by using `ImGui.__Internal`. Because I knew codegen wasn't always going to be perfect, I deliberately went of my way to make internals visible, so people can access the raw data.

**Comment by DestroyerDarkNess** [comment]
Bro!!! Your code solved the problem.

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/832c11f9-1748-4fa1-a5f2-d172e3e7b3aa)

![image](https://github.com/Sewer56/DearImguiSharp/assets/32405118/6432c221-6233-4bab-8963-4c62f5102173)

By the way, I don't want to use Imgui.NET, for two reasons:

1) lacks the implementations for dx9-12, gl and vulkan. I tried to compile cimgui with only the dx9 backend and it didn't work. On the other hand, DearImguiSharp has everything I need.

2) It is very restrictive with other .NET languages, for example VB.NET, most Properties appear as read-only from VB, however with DearImguiSharp that does not happen.

I guess I'll correct the little mistakes.

By the way, please don't abandon DearImguiSharp. I know you're very busy, but if you ever have a vacation, update this.

You can close this Issue if you wish.

**Comment by Sewer56** [comment]
I update this library when I use it every once in a while. Right now, this won't be the case for quite a while, so I won't expect any updates till late 2025.

That said, I'll happily accept PRs. The readme of this repo even has instructions on how to upgrade ImGui and the wrapper itself, so you can easily update the library to use the latest version of ImGui.

There's still a bunch of improvements to be done too, 

- https://github.com/Sewer56/DearImguiSharp/pull/3

One of our sibling projects for instance needed a more customized ImGui wrapper, so they started with some of DearImGuiSharp, and made even further improvements to the code generation.

I'd be very happy personally if some of these improvements were backported, especially the documentation and efficiency ones.

Merging with sibling project is of course an option too. It may be easier to merge this project into the sibling even, given that most of the benefits here relate to having backends, which is mostly on the native side.

Splitting the native side with 1 backend per DLL might also be a great option, some backends are costly in terms of code size.

**Comment by DestroyerDarkNess** [comment]
Thanks for responding, I guess I'll wait until next year. I will open this issue again at the end of next year. XD
